spring:
  application:
    name: API_Gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowed-origin-patterns:
                  - "*"
                allowed-methods:
                  - "*"
                allowed-headers:
                  - "*"
                exposed-headers:
                  - "*"
          routes:
            - id: user-management-service
              uri: lb://UserManagementService
              predicates:
                - Path=/auth/**,/logistics/auth/**,/logistics/api/v1/users/**

            - id: parcel-service
              uri: lb://ParcelService
              predicates:
                - Path=/logistics/api/v1/agencies/**,/logistics/api/v1/parcels/**,/logistics/api/v1/routes/**
              filters:
                - name: JwtFilter

            - id: delivery-service
              uri: lb://DeliveryService
              predicates:
                - Path=/logistics/api/v1/trips/**
              filters:
                - name: JwtFilter

            - id: payment-service
              uri: lb://PaymentService
              predicates:
                - Path=/logistics/api/v1/payments/**
              filters:
                - name: JwtFilter

            - id: notification-service
              uri: lb://NotificationService
              predicates:
                - Path=/logistics/api/v1/notifications/**
              filters:
                - name: JwtFilter
server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: 4tQT9UMVUmtI8FnJRFgN+Vg3mgyJB1Rlmp94Qfe3Gjk=