spring:
  application:
    name: NotificationService
  datasource:
    url: jdbc:mysql://localhost:3307/logistics_db
    username: root
    password: weber12?
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
  mail:
    host: smtp.gmail.com
    port: 587
    username: fotsingweber4@gmail.com
    password: weber12?
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

firebase:
  credentials-path: ${FIREBASE_CREDENTIALS_PATH:firebase-service-account-logistic-tracking.json}
  project-id: ${FIREBASE_PROJECT_ID:logistic-tracking-pr3}

africastalking:
  username: sandbox
  api-key: atsk_24c766b1780cf00d1bb58b026898504dff86f397272acc37b24217cc49a3102d56f73979
  sender-id: your-sender-id
