spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    addresses: ${RABBITMQ_URL}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${RENDER_EXTERNAL_HOSTNAME}

management:
  endpoints:
    web:
      exposure:
        include: health,info